### ISSUE TITLE
Dont load `migrations` by default

### ISSUE THREAD

**Issue by myckhel** [myckhel/laravel-chat-system#10]
Prevent loading migrations by default to encourage users publish migration files and modify.

when user run `php artisan migrate`, automatically it applies to chatsystem migrations without the user publishing the migration files.

it would be a good idea to always encourage the users to publish migration files so that they can modify the migrations to their tastes.

so when user run `php artisan migrate` it wouldn't automatically applied to chatsystem migrations until user manually publish the migration files.

**Comment by hmreumann** [comment]
Hi myckhel, i've made some changes in order to "Prevent loading migrations by default".

1. First i comented the loadMigrationsFrom from the boot method on the Service Provider.
2. Then i renamed the migrations removing the timestamps and adding .stub at the end... ie: "create_conversation_users_table.php.stub".
3. Then i added each one of the migrations to the bootForConsole() function in the Service Provider.

After testing it, I'll submit the pull request.
